var _templateObject = _taggedTemplateLiteral(['\n  .beerspick {\n    /* use !important to prevent issues with browser extensions that change fonts */\n    font-family: \'beerspick\' !important;\n    speak: none;\n    font-style: normal;\n    font-weight: normal;\n    font-variant: normal;\n    text-transform: none;\n    line-height: 1;\n\n    /* Better Font Rendering =========== */\n    -webkit-font-smoothing: antialiased;\n    -moz-osx-font-smoothing: grayscale;\n  }\n\n  .beerspick-beerspick_logo_about:before {\n    content: \'\\e907\';\n  }\n  .beerspick-beerspick_logo_header:before {\n    content: \'\\e900\';\n  }\n  .beerspick-instagram_logo:before {\n    content: \'\\e901\';\n  }\n  .beerspick-tel:before {\n    content: \'\\e902\';\n  }\n  .beerspick-beerspick_logo_footer:before {\n    content: \'\\e903\';\n    color: #fff;\n  }\n  .beerspick-envelope:before {\n    content: \'\\e904\';\n    color: #f6c914;\n  }\n  .beerspick-facebook_logo:before {\n    content: \'\\e905\';\n  }\n  .beerspick-location-arrow:before {\n    content: \'\\e906\';\n    color: #ff8748;\n  }\n'], ['\n  .beerspick {\n    /* use !important to prevent issues with browser extensions that change fonts */\n    font-family: \'beerspick\' !important;\n    speak: none;\n    font-style: normal;\n    font-weight: normal;\n    font-variant: normal;\n    text-transform: none;\n    line-height: 1;\n\n    /* Better Font Rendering =========== */\n    -webkit-font-smoothing: antialiased;\n    -moz-osx-font-smoothing: grayscale;\n  }\n\n  .beerspick-beerspick_logo_about:before {\n    content: \'\\\\e907\';\n  }\n  .beerspick-beerspick_logo_header:before {\n    content: \'\\\\e900\';\n  }\n  .beerspick-instagram_logo:before {\n    content: \'\\\\e901\';\n  }\n  .beerspick-tel:before {\n    content: \'\\\\e902\';\n  }\n  .beerspick-beerspick_logo_footer:before {\n    content: \'\\\\e903\';\n    color: #fff;\n  }\n  .beerspick-envelope:before {\n    content: \'\\\\e904\';\n    color: #f6c914;\n  }\n  .beerspick-facebook_logo:before {\n    content: \'\\\\e905\';\n  }\n  .beerspick-location-arrow:before {\n    content: \'\\\\e906\';\n    color: #ff8748;\n  }\n']);

function _taggedTemplateLiteral(strings, raw) { return Object.freeze(Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })); }

import { css } from 'styled-components';

/**
 * Should add one more \, cause it's javascript !
 */
var Style = css(_templateObject);

export default Style;